### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by FreekingDean** [interagent/schematic#53]
Hi all!
I noticed that this project has had very little activity in the past year & wanted to know if this was still a project that is maintained.

**Comment by bernerdschaefer** [comment]
@FreekingDean schematic works and is still in use, for example, to generate the [heroku-go](https://github.com/heroku/heroku-go) client used by terraform and others. There's no backlog of ongoing work for it, but we do monitor new issues and pull requests as they come up.
